/**
 * tailwind.config.js — NEED Stitch Civic Cooperative design system.
 */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        // Stitch Official Color Tokens
        surface: '#FAF8FF',
        'surface-dim': '#D2D9F4',
        'surface-bright': '#FAF8FF',
        'surface-container-lowest': '#FFFFFF',
        'surface-container-low': '#F2F3FF',
        'surface-container': '#EAEDFF',
        'surface-container-high': '#E2E7FF',
        'surface-container-highest': '#DAE2FD',
        'on-surface': '#131B2E',
        'on-surface-variant': '#3E4943',
        'inverse-surface': '#283044',
        'inverse-on-surface': '#EEF0FF',
        outline: '#6E7A72',
        'outline-variant': '#BDC9C1',
        'surface-tint': '#006C4B',
        primary: '#005F41',
        'on-primary': '#FFFFFF',
        'primary-container': '#007A55',
        'on-primary-container': '#A3FFD2',
        'inverse-primary': '#79D9AD',
        secondary: '#855300',
        'on-secondary': '#FFFFFF',
        'secondary-container': '#FEA619',
        'on-secondary-container': '#684000',
        tertiary: '#005F40',
        'on-tertiary': '#FFFFFF',
        'tertiary-container': '#007A53',
        'on-tertiary-container': '#A3FFD0',
        error: '#BA1A1A',
        'on-error': '#FFFFFF',
        'error-container': '#FFDAD6',
        'on-error-container': '#93000A',
        'primary-fixed': '#95F6C8',
        'primary-fixed-dim': '#79D9AD',
        'on-primary-fixed': '#002114',
        'on-primary-fixed-variant': '#005137',
        'secondary-fixed': '#FFDDB8',
        'secondary-fixed-dim': '#FFB95F',
        'on-secondary-fixed': '#2A1700',
        'on-secondary-fixed-variant': '#653E00',
        'tertiary-fixed': '#6FFBBE',
        'tertiary-fixed-dim': '#4EDEA3',
        'on-tertiary-fixed': '#002113',
        'on-tertiary-fixed-variant': '#005236',
        background: '#FAF8FF',
        'on-background': '#131B2E',
        'surface-variant': '#DAE2FD',

        // Legacy compatibility aliases
        ink: {
          DEFAULT: '#131B2E',
          900: '#0F172A',
          800: '#131B2E',
          700: '#334155',
          600: '#475569',
        },
        brand: {
          50: '#E6F7F0',
          100: '#B8EBD7',
          200: '#8DDEC0',
          500: '#007A55',
          600: '#005F41',
          700: '#005137',
        },
        marigold: {
          50: '#FFF4DF',
          400: '#FFB95F',
          500: '#FEA619',
          600: '#855300',
        },
        verified: '#007A55',
        pending: '#C98A04',
        rejected: '#BA1A1A',
        paper: '#FAF8FF',
        line: '#BDC9C1',
        muted: '#64748B',
      },
      fontFamily: {
        sans: ['"Plus Jakarta Sans"', 'system-ui', 'sans-serif'],
        display: ['"Plus Jakarta Sans"', 'system-ui', 'sans-serif'],
        mono: ['"Plus Jakarta Sans"', 'ui-monospace', 'monospace'],
        'display-lg': ['"Plus Jakarta Sans"'],
        'display-lg-mobile': ['"Plus Jakarta Sans"'],
        'headline-xl': ['"Plus Jakarta Sans"'],
        'headline-xl-mobile': ['"Plus Jakarta Sans"'],
        'headline-lg': ['"Plus Jakarta Sans"'],
        'headline-md': ['"Plus Jakarta Sans"'],
        'headline-sm': ['"Plus Jakarta Sans"'],
        'body-lg': ['"Plus Jakarta Sans"'],
        'body-md': ['"Plus Jakarta Sans"'],
        'body-sm': ['"Plus Jakarta Sans"'],
        'label-lg': ['"Plus Jakarta Sans"'],
        'label-md': ['"Plus Jakarta Sans"'],
        'label-caps': ['"Plus Jakarta Sans"'],
        'metric-val': ['"Plus Jakarta Sans"'],
      },
      screens: {
        sm: '640px',
        md: '768px',
        lg: '1024px',
        xl: '1280px',
        '2xl': '1440px',
        '3xl': '1920px',
      },
      // Semantic type scale. Sizes were originally tuned for a 1280px design
      // canvas; now that the container goes to 1440/1680/1840 the content-
      // bearing steps are a notch larger so text does not read as small print
      // on a big display. Caps/label steps stay small on purpose — they are
      // labels, not body copy.
      fontSize: {
        'display-lg': ['60px', { lineHeight: '66px', letterSpacing: '-0.03em', fontWeight: '800' }],
        'display-lg-mobile': ['34px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'headline-xl': ['42px', { lineHeight: '50px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'headline-xl-mobile': ['26px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.015em', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-sm': ['19px', { lineHeight: '27px', fontWeight: '600' }],
        'body-lg': ['19px', { lineHeight: '30px', fontWeight: '400' }],
        'body-md': ['17px', { lineHeight: '28px', fontWeight: '400' }],
        'body-sm': ['15px', { lineHeight: '24px', fontWeight: '400' }],
        'label-lg': ['15px', { lineHeight: '22px', fontWeight: '600' }],
        'label-md': ['13.5px', { lineHeight: '19px', fontWeight: '600' }],
        'label-caps': ['11px', { lineHeight: '14px', letterSpacing: '0.08em', fontWeight: '700' }],
        'metric-val': ['32px', { lineHeight: '38px', letterSpacing: '-0.02em', fontWeight: '800' }],
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        sm: '0.25rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.25rem',
        '2xl': '1.5rem',
        '3xl': '2rem',
        full: '9999px',
      },
      spacing: {
        'space-2xs': '0.25rem',
        'space-xs': '0.5rem',
        'space-sm': '0.75rem',
        'space-md': '1rem',
        'space-lg': '1.5rem',
        'space-xl': '2rem',
        'space-2xl': '3rem',
        'space-3xl': '4rem',
        'gutter-mobile': '1rem',
        'gutter-desktop': '1.5rem',
        'container-max': '1440px',
      },
      boxShadow: {
        sm: '0 1px 2px 0 rgba(15, 23, 42, 0.04)',
        DEFAULT: '0 1px 3px 0 rgba(15, 23, 42, 0.06), 0 1px 2px -1px rgba(15, 23, 42, 0.04)',
        md: '0 4px 6px -1px rgba(15, 23, 42, 0.06), 0 2px 4px -2px rgba(15, 23, 42, 0.04)',
        lg: '0 10px 15px -3px rgba(15, 23, 42, 0.06), 0 4px 6px -4px rgba(15, 23, 42, 0.03)',
        xl: '0 20px 25px -5px rgba(15, 23, 42, 0.08), 0 8px 10px -6px rgba(15, 23, 42, 0.03)',
        card: '0 1px 3px 0 rgba(15, 23, 42, 0.04), 0 1px 2px -1px rgba(15, 23, 42, 0.02)',
        lift: '0 10px 15px -3px rgba(15, 23, 42, 0.06), 0 4px 6px -4px rgba(15, 23, 42, 0.03)',
      },
      // Kept in step with the .container-page ladder in index.css.
      maxWidth: {
        content: '1440px',
        'container-max': '1680px',
        'site-max': '1840px',
        prose: '46rem',
      },
      keyframes: {
        'fade-in': {
          from: { opacity: '0' },
          to: { opacity: '1' },
        },
      },
      animation: {
        'fade-in': 'fade-in 180ms ease-out',
      },
    },
  },
  plugins: [],
}
